/**
 * Error codes enum
 * Centralized error code definitions for consistent error handling
 */
export enum ErrorCode {
  // Validation Errors (400)
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_INPUT = 'INVALID_INPUT',

  // Authentication Errors (401)
  UNAUTHORIZED = 'UNAUTHORIZED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',

  // Authorization Errors (403)
  FORBIDDEN = 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',

  // Not Found Errors (404)
  NOT_FOUND = 'NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  TRANSACTION_NOT_FOUND = 'TRANSACTION_NOT_FOUND',

  // Conflict Errors (409)
  CONFLICT = 'CONFLICT',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  CATEGORY_NAME_EXISTS = 'CATEGORY_NAME_EXISTS',

  // Business Logic Errors (422)
  CANNOT_DELETE_DEFAULT_CATEGORY = 'CANNOT_DELETE_DEFAULT_CATEGORY',
  CANNOT_DELETE_CATEGORY_WITH_TRANSACTIONS = 'CANNOT_DELETE_CATEGORY_WITH_TRANSACTIONS',
  INVALID_CATEGORY = 'INVALID_CATEGORY',
  PASSWORD_MISMATCH = 'PASSWORD_MISMATCH',

  // Server Errors (500)
  SERVER_ERROR = 'SERVER_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}

